PhatHanhSach/PhatHanhSach/Controllers/DoanhThuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhatHanhSach.Models;
using PhatHanhSach.Models.ViewModels;

namespace PhatHanhSach.Controllers
{
    public class DoanhThuController : Controller
    {
        // GET: DoanhThu
        PhatHanhSachEntities db = new PhatHanhSachEntities();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ThongKe(FormCollection f)
        {
            String[] bd = f["TuNgay"].ToString().Split('-');
            DateTime datebd = new DateTime(int.Parse(bd[2]), int.Parse(bd[1]), int.Parse(bd[0]));

            String[] kt = f["DenNgay"].ToString().Split('-');
            DateTime datekt = new DateTime(int.Parse(kt[2]), int.Parse(kt[1]), int.Parse(kt[0]));
            
            var px = db.PHIEUXUATs.Where(n => n.NgayXuat >= datebd && n.NgayXuat <= datekt).ToList();
            ViewBag.TuNgay = datebd.ToString("dd/MM/yyyy");
            ViewBag.DenNgay = datekt.ToString("dd/MM/yyyy");
            return View(px);
        }

        public ActionResult XemChiTiet(int? MaPX)
        {
            var px = db.PHIEUXUATs.SingleOrDefault(n => n.MaPX == MaPX);
            ViewBag.DS_CTPhieuXuat = px.CT_PHIEUXUAT;
            return View(px);
        }
    }
}

PhatHanhSach/PhatHanhSach/Views/DoanhThu/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    int? TongThu = 0;
}

<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
<link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css" rel="Stylesheet" type="text/css" />

<script>
    $(document).ready(function () {
        $(".datepicker").datepicker({
            dateFormat: 'dd-mm-yy',
            changeMonth: true, //Tùy chọn này cho phép người dùng chọn tháng
            changeYear: true //Tùy chọn này cho phép người dùng lựa chọn từ phạm vi năm
        });

        $("#btnThongKe").click(function () {
            if ($("#TuNgay").datepicker("getDate") == null || $("#DenNgay").datepicker("getDate") == null) {
                alert("Vui lòng nhập đầy đủ thời gian");
                return false;
            }
            if ($("#TuNgay").datepicker("getDate") > $("#DenNgay").datepicker("getDate"))
            {
                alert("Ngày bắt đầu phải < ngày kết thúc");
                return false;
            }
        });
    })
</script>

<h2>Thống kê doanh thu</h2>
<form class="form-horizontal" action="@Url.Action("ThongKe","DoanhThu")" method="POST">
    <div class="row">
        <div class="form-group col-md-12">
            <div class="col-md-2" style="text-align: center">
                <label class="control-label">Thống kê thời gian từ</label>
            </div>
            <div class="col-md-4">
                <input type="text" id="TuNgay" name="TuNgay" class="form-control datepicker" />
            </div>
        </div>

        <div class="form-group col-md-12">
            <div class="col-md-2" style="text-align: center">
                <label class="control-label">đến</label>
            </div>
            <div class="col-md-4">
                <input type="text" id="DenNgay" name="DenNgay" class="form-control datepicker" />
            </div>
        </div>

        <div class="text-center" style="float: right">
            <button id="btnThongKe" formmethod="post" formaction="ThongKe" class="btn btn-primary ">Thống kê</button>
        </div>
    </div>
</form>

PhatHanhSach/PhatHanhSach/Views/DoanhThu/ThongKe.cshtml
@using PhatHanhSach.Models
@model IEnumerable<PHIEUXUAT>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    int? TongThu = 0;
}

<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
<link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css" rel="Stylesheet" type="text/css" />

<script>
    $(document).ready(function () {
        $(".datepicker").datepicker({
            dateFormat: 'dd-mm-yy',
            changeMonth: true, //Tùy chọn này cho phép người dùng chọn tháng
            changeYear: true //Tùy chọn này cho phép người dùng lựa chọn từ phạm vi năm
        });

        $("#TuNgay").datepicker("setDate", '@ViewBag.DatePickerBD');
        $("#DenNgay").datepicker("setDate", '@ViewBag.DatePickerKT');

        $("#btnThongKe").click(function () {
            if ($("#TuNgay").datepicker("getDate") == null || $("#DenNgay").datepicker("getDate") == null) {
                alert("Vui lòng nhập đầy đủ thời gian");
                return false;
            }
            if ($("#TuNgay").datepicker("getDate") > $("#DenNgay").datepicker("getDate")) {
                alert("Ngày bắt đầu phải < ngày kết thúc");
                return false;
            }
        });
    })
</script>

@using (@Html.BeginForm())
{
    <h2>Thống kê doanh thu từ ngày @ViewBag.TuNgay đến @ViewBag.DenNgay</h2>

    <div class="form-group col-md-12">
        <div class="col-md-2" style="text-align: center">
            <label class="control-label">Thống kê thời gian từ</label>
        </div>
        <div class="col-md-4">
            <input type="text" id="TuNgay" name="TuNgay" class="form-control datepicker" />
        </div>
    </div>

    <div class="form-group col-md-12">
        <div class="col-md-2" style="text-align: center">
            <label class="control-label">đến</label>
        </div>
        <div class="col-md-4">
            <input type="text" id="DenNgay" name="DenNgay" class="form-control datepicker" />
        </div>
    </div>

    <div class="text-center" style="float: right">
        <button id="btnThongKe" formmethod="post" formaction="ThongKe" class="btn btn-primary ">Thống kê</button>
    </div>

    <table width="100%" class="table table-bordered">
        <tr>
            <th>Mã phiếu xuất</th>
            <th>Ngày Xuất</th>
            <th>Tên đại lý</th>
            <th>Tổng Tiền</th>
            <th></th>
        </tr>
        @foreach (PHIEUXUAT s in Model)
        {
            <tr>
                <td>@s.MaPX</td>
                <td>@s.NgayXuat.Value.ToString("dd/MM/yyyy")</td>
                <td>@s.DAILY.Ten</td>
                <td>@s.TongTien.Value.ToString("#,##") VNĐ</td>
                <td>@Html.ActionLink("Xem Chi Tiết", "XemChiTiet", new { @MaPX = s.MaPX })</td>
            </tr>
            TongThu += s.TongTien;
        }
    </table>
    if (TongThu != 0)
    {
        <h2 style="float: right">Tổng thu: @TongThu.Value.ToString("#,##") VNĐ</h2>
        <br />
    }
}
<style>
    table {
        width: 100%;
        border: 1px 1px solid;
        font-size: 20px;
    }

        table img {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 130px;
            height: 200px;
        }

        table th {
            text-align: center;
        }
</style>

PhatHanhSach/PhatHanhSach/Views/DoanhThu/XemChiTiet.cshtml
@using PhatHanhSach.Models
@model PHIEUXUAT
@{
    ViewBag.Title = "XemChiTiet";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    List<CT_PHIEUXUAT> list = ViewBag.DS_CTPhieuXuat as List<CT_PHIEUXUAT>;
}

<div class="form-group col-md-12">
    <div class="col-md-2" style="text-align: center">
        <label class="control-label">Đại lý</label>
    </div>
    <div class="col-md-4">
        @*@Html.DropDownListFor(m => m.MaDL, ViewBag.DS_DaiLy as SelectList, new { @class = "form-control" })*@
        <input type="text" value="@Model.DAILY.Ten" class="form-control" disabled="disabled"/>
    </div>
</div>

<div class="form-group col-md-12">
    <div class="col-md-2" style="text-align: center">
        <label class="control-label">Ngày xuất</label>
    </div>
    <div class="col-md-4">
        <input type="text" value="@Model.NgayXuat.Value.ToString("dd/MM/yyyy")" class="form-control" disabled="disabled"/>
    </div>
</div>

<div style="clear:both">
    <br />
</div>

<table class="table table-bordered text-center">
    <tr>
        <th>Mã Sách</th>
        <th>Tên Sách</th>
        <th>Giá xuất</th>
        <th>Số Lượng</th>
        <th>Thành Tiền</th>
    </tr>
    @foreach (CT_PHIEUXUAT s in ViewBag.DS_CTPhieuXuat as IEnumerable<CT_PHIEUXUAT>)
    {
        <tr>
            <td>@s.MaSach</td>
            <td>@s.SACH.TenSach</td>
            <td>@s.DonGia.Value.ToString("#,##")</td>
            <td>@s.SLXuat</td>
            <td>@s.ThanhTien.Value.ToString("#,##")</td>
        </tr>
    }
</table>
<h2 style="float: right">Tổng tiền: @Model.TongTien.Value.ToString("#,##") VNĐ</h2>


<style>
    table {
        width: 100%;
        border: 1px 1px solid;
        font-size: 20px;
    }

    table img {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 130px;
        height: 200px;
    }

    table th {
        text-align: center;
    }
</style>